smel-db:
  image: postgres:9.5
  container_name: smel-db
  environment:
    - POSTGRES_PASSWORD=SM3L_yUh-L4trr
    - POSTGRES_USER=smel
    - POSTGRES_DB=smel

smel-www:
  build: smel-www
  links:
    - smel-db
  volumes:
    - "./smel-www/code:/var/www"

smel-proxy:
  image: annixa/docker-nginx-letsencrypt-proxy
  ports:
    - 80:80
    - 443:443
  container_name: docker-nginx-letsencrypt-proxy
  log_opt:
    max-size: 50k
  environment:
    # - LE_TEST=true # LE is rate limited. While doing development, be sure to set testing mode so requests don't count against our quota.
    - LE_EMAIL=spaceapps.sandiego@gmail.com
    - LE_DOMAIN=smel.final-frontier.space
    - PROXY_DEST=http://smel-www/
    - SLACK_NOTIFICATIONS_INFRA_URL=https://hooks.slack.com/services/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 # Be sure to fill this in using your URL for the slack webhook integration
  volumes:
    - "/etc/letsencrypt"
