smel-db:
  image: mdillon/postgis
  container_name: smel-db
  env_file: smel-db.env

smel-www:
  build: smel-www
  container_name: smel-www
  links:
    - smel-db
  volumes:
    - "./smel-www:/var/www"
  ports:
    - "8888:8888"
  env_file:
    - smel.env
    - smel-db.env

# smel-proxy:
#   image: annixa/docker-nginx-letsencrypt-proxy
#   container_name: smel-proxy
#   links:
#     - smel-www
#   ports:
#     - 80:80
#     - 443:443
#   log_opt:
#     max-size: 50k
#   environment:
#     # - LE_TEST=true # LE is rate limited. While doing development, be sure to set testing mode so requests don't count against our quota.
#     - LE_EMAIL=spaceapps.sandiego@gmail.com
#     - LE_DOMAIN=smel.final-frontier.space
#     - PROXY_DEST=http://smel-www:8888/
#     - SLACK_NOTIFICATIONS_INFRA_URL=https://hooks.slack.com/services/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 # Be sure to fill this in using your URL for the slack webhook integration
#   volumes:
#     - "/etc/letsencrypt"
